# Generated by Django 5.0.6 on 2024-06-30 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='allusername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalone.personaldetails'),
        ),
    ]
