# Generated by Django 5.0.6 on 2024-07-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalone', '0003_alter_personaldetails_ename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='ename',
            field=models.CharField(max_length=100),
        ),
    ]
