# Generated by Django 5.0.6 on 2024-07-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalone', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverpic', models.ImageField(upload_to='img')),
            ],
        ),
    ]
