# Generated by Django 5.0.6 on 2024-07-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalone', '0006_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverpic',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
