# Generated by Django 5.0.6 on 2024-07-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalone', '0007_profile_coverpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='textbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=1000)),
            ],
        ),
    ]
