# Generated by Django 5.0.6 on 2024-07-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalone', '0008_textbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbox',
            name='post',
            field=models.CharField(max_length=1000),
        ),
    ]
