# Generated by Django 5.0.6 on 2024-07-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalone', '0010_friendrequest_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='friendrequest1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to='finalone.personaldetails')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touser', to='finalone.personaldetails')),
            ],
        ),
    ]
