# Generated by Django 5.0.6 on 2024-07-15 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalone', '0014_profile_from_user_profile_to_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='frndrqst',
            field=models.ManyToManyField(blank=True, related_name='frndrqst', to=settings.AUTH_USER_MODEL),
        ),
    ]
