# Generated by Django 5.0.6 on 2024-07-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalone', '0015_profile_frndrqst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
