# Generated by Django 5.0.6 on 2024-07-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalone', '0016_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='des',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
