# Generated by Django 5.0.6 on 2024-07-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalone', '0017_alter_profile_des_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
