# Generated by Django 5.0.6 on 2024-07-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalone', '0018_friendship_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
