# Generated by Django 5.0.6 on 2024-07-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalone', '0020_post_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post1',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
