# Generated by Django 5.0.6 on 2024-07-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalone', '0022_alter_comment_author_alter_like_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
